CREATE SEQUENCE SQ_PERFIL;
CREATE SEQUENCE SQ_USUARIO;
CREATE SEQUENCE SQ_EMAIL_USUARIO;
CREATE SEQUENCE SQ_SUPERMERCADO;
CREATE SEQUENCE SQ_PRODUTO;
CREATE SEQUENCE SQ_PRODUTO_SUPERMERCADO;

CREATE TABLE TB_PERFIL(ID_PERFIL INTEGER NOT NULL , DESCRICAO VARCHAR(50) NOT NULL );
ALTER TABLE TB_PERFIL ADD CONSTRAINT PK_PERFIL PRIMARY KEY(ID_PERFIL);

CREATE TABLE TB_USUARIO(ID_USUARIO INTEGER NOT NULL , NOME VARCHAR(255) NOT NULL , DATA_NASCIMENTO DATE NOT NULL, LOGIN VARCHAR(50) NOT NULL, SENHA VARCHAR(50) NOT NULL, ID_PERFIL INTEGER NOT NULL );
ALTER TABLE TB_USUARIO ADD CONSTRAINT UNQ_LOGIN UNIQUE(LOGIN);
ALTER TABLE TB_USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO);
ALTER TABLE TB_USUARIO ADD CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY(ID_PERFIL) REFERENCES TB_PERFIL(ID_PERFIL);

CREATE TABLE TB_EMAIL(ID_EMAIL INTEGER NOT NULL , EMAIL VARCHAR(50) NOT NULL , ID_USUARIO INTEGER NOT NULL );
ALTER TABLE TB_EMAIL ADD CONSTRAINT PK_EMAIL PRIMARY KEY(ID_EMAIL);
ALTER TABLE TB_EMAIL ADD CONSTRAINT FK_USUARIO_EMAIL FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO);

CREATE TABLE TB_SUPERMERCADO(ID_SUPERMERCADO INTEGER NOT NULL, NOME VARCHAR(50) NOT NULL, ENDERECO VARCHAR(250), LOCALIZACAO VARCHAR(500));
ALTER TABLE TB_SUPERMERCADO ADD CONSTRAINT PK_SUPERMERCADO PRIMARY KEY(ID_SUPERMERCADO);

CREATE TABLE TB_PRODUTO(ID_PRODUTO INTEGER NOT NULL, NOME VARCHAR(50) NOT NULL , DESCRICAO VARCHAR(255) , MARCA VARCHAR(50) NOT NULL );
ALTER TABLE TB_PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO);

CREATE TABLE TB_PRODUTO_SUPERMERCADO(ID_PRODUTO_SUPERMERCADO INTEGER NOT NULL, ID_PRODUTO INTEGER NOT NULL, ID_SUPERMERCADO INTEGER NOT NULL, QUANTIDADE INTEGER NOT NULL , PRECO DECIMAL(9,2) NOT NULL , DATA_VALIDADE DATE NOT NULL )
ALTER TABLE TB_PRODUTO_SUPERMERCADO ADD CONSTRAINT PK_PRODUTO_SUPERMERCADO PRIMARY KEY (ID_PRODUTO_SUPERMERCADO);
ALTER TABLE TB_PRODUTO_SUPERMERCADO ADD CONSTRAINT FK_PRODUTO_SUPERMERCADO FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);
ALTER TABLE TB_PRODUTO_SUPERMERCADO ADD CONSTRAINT FK_SUPERMERCADO_PRODUTO FOREIGN KEY(ID_SUPERMERCADO) REFERENCES TB_SUPERMERCADO(ID_SUPERMERCADO);

COMMIT;