CREATE SEQUENCE SQ_PERFIL;
CREATE SEQUENCE SQ_USUARIO;
CREATE SEQUENCE SQ_EMAIL_USUARIO;
CREATE SEQUENCE SQ_SUPERMERCADO;
CREATE SEQUENCE SQ_PRODUTO;
CREATE SEQUENCE SQ_PRODUTO_SUPERMERCADO;

CREATE TABLE TB_PERFIL(ID_PERFIL INTEGER NOT NULL , DESCRICAO VARCHAR(50) NOT NULL );
ALTER TABLE TB_PERFIL ADD CONSTRAINT PK_PERFIL PRIMARY KEY(ID_PERFIL);
create or replace TRIGGER PERFIL_TRG BEFORE INSERT ON TB_PERFIL FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.ID_PERFIL IS NULL THEN SELECT SQ_PERFIL.NEXTVAL INTO :NEW.ID_PERFIL FROM DUAL; END IF; END COLUMN_SEQUENCES; END;

CREATE TABLE TB_USUARIO(ID_USUARIO INTEGER NOT NULL , NOME VARCHAR(255) NOT NULL , DATA_NASCIMENTO DATE NOT NULL, LOGIN VARCHAR(50) NOT NULL, SENHA VARCHAR(50) NOT NULL, ID_PERFIL INTEGER NOT NULL );
ALTER TABLE TB_USUARIO ADD CONSTRAINT UNQ_LOGIN UNIQUE(LOGIN);
ALTER TABLE TB_USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO);
ALTER TABLE TB_USUARIO ADD CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY(ID_PERFIL) REFERENCES TB_PERFIL(ID_PERFIL);
create or replace TRIGGER USUARIO_TRG BEFORE INSERT ON TB_USUARIO FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.ID_USUARIO IS NULL THEN SELECT SQ_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL; END IF; END COLUMN_SEQUENCES; END;


CREATE TABLE TB_EMAIL(ID_EMAIL INTEGER NOT NULL , EMAIL VARCHAR(50) NOT NULL , ID_USUARIO INTEGER NOT NULL );
ALTER TABLE TB_EMAIL ADD CONSTRAINT PK_EMAIL PRIMARY KEY(ID_EMAIL);
ALTER TABLE TB_EMAIL ADD CONSTRAINT FK_USUARIO_EMAIL FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO);
create or replace TRIGGER EMAIL_TRG BEFORE INSERT ON TB_EMAIL FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.ID_EMAIL IS NULL THEN SELECT SQ_EMAIL_USUARIO.NEXTVAL INTO :NEW.ID_EMAIL FROM DUAL; END IF; END COLUMN_SEQUENCES; END;


CREATE TABLE TB_SUPERMERCADO(ID_SUPERMERCADO INTEGER NOT NULL, NOME VARCHAR(50) NOT NULL, ENDERECO VARCHAR(250), LOCALIZACAO VARCHAR(500));
ALTER TABLE TB_SUPERMERCADO ADD CONSTRAINT PK_SUPERMERCADO PRIMARY KEY(ID_SUPERMERCADO);
create or replace TRIGGER SUPERMERCADO_TRG BEFORE INSERT ON TB_SUPERMERCADO FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.ID_SUPERMERCADO IS NULL THEN SELECT SQ_SUPERMERCADO.NEXTVAL INTO :NEW.ID_SUPERMERCADO FROM DUAL; END IF; END COLUMN_SEQUENCES; END;


CREATE TABLE TB_PRODUTO(ID_PRODUTO INTEGER NOT NULL, NOME VARCHAR(50) NOT NULL , DESCRICAO VARCHAR(255) , MARCA VARCHAR(50) NOT NULL );
ALTER TABLE TB_PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO);
create or replace TRIGGER PRODUTOO_TRG BEFORE INSERT ON TB_PRODUTO FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.ID_PRODUTO IS NULL THEN SELECT SQ_PRODUTO.NEXTVAL INTO :NEW.ID_PRODUTO FROM DUAL; END IF; END COLUMN_SEQUENCES; END;


CREATE TABLE TB_PRODUTO_SUPERMERCADO(ID_PRODUTO_SUPERMERCADO INTEGER NOT NULL, ID_PRODUTO INTEGER NOT NULL, ID_SUPERMERCADO INTEGER NOT NULL, QUANTIDADE INTEGER NOT NULL , PRECO DECIMAL(9,2) NOT NULL , DATA_VALIDADE DATE NOT NULL )
ALTER TABLE TB_PRODUTO_SUPERMERCADO ADD CONSTRAINT PK_PRODUTO_SUPERMERCADO PRIMARY KEY (ID_PRODUTO_SUPERMERCADO);
ALTER TABLE TB_PRODUTO_SUPERMERCADO ADD CONSTRAINT FK_PRODUTO_SUPERMERCADO FOREIGN KEY(ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO);
ALTER TABLE TB_PRODUTO_SUPERMERCADO ADD CONSTRAINT FK_SUPERMERCADO_PRODUTO FOREIGN KEY(ID_SUPERMERCADO) REFERENCES TB_SUPERMERCADO(ID_SUPERMERCADO);
create or replace TRIGGER PRODUTO_SUPERMERCADO_TRG BEFORE INSERT ON TB_PRODUTO_SUPERMERCADO FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN IF :NEW.ID_PRODUTO_SUPERMERCADO IS NULL THEN SELECT SQ_PRODUTO_SUPERMERCADO.NEXTVAL INTO :NEW.ID_PRODUTO_SUPERMERCADO FROM DUAL; END IF; END COLUMN_SEQUENCES; END;

COMMIT;